service: twitter-service

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:*
      Resource: "*"
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
    packRequirements: false
functions:
  app:

    handler: wsgi.handler
    events:
      - http:
          path: /sendTweet
          method: ANY
          cors: true
      - http:
          path: /getTweet
          method: ANY
          cors: true
      - http:
          path: /deleteTweet
          method: ANY
          cors: true
      - http: 'ANY {proxy+}'